### ISSUE TITLE
Smith2018ArticularContactForce methods depending on Position Stage are not working in MATLAB

### ISSUE THREAD

**Issue by modenaxe** [opensim-jam-org/opensim-core#6]
Hello,
I have noticed that all methods taking a state as input realised at Position Stage are not working in MATLAB and they throw the similar error pointing at a mismatch of versions of the Stage.
This is the error thrown if I am trying to compute the triangle proximity:
```
Java exception occurred:
java.lang.RuntimeException: SimTK Exception thrown at State.cpp:974:
  Error detected by Simbody method getCacheEntry: State Cache entry was out of date at Stage Position. This entry depends on version 7 of
  Stage Position but was last updated at version 0.
  (Required condition 'version == m_dependsOnVersionWhenLastComputed' was not met.)


	at org.opensim.modeling.opensimSimulationJNI.Smith2018ArticularContactForce_getTargetTriangleProximity(Native Method)

	at org.opensim.modeling.Smith2018ArticularContactForce.getTargetTriangleProximity(Smith2018ArticularContactForce.java:862)
```
and this is for the potential energy:
```
Java exception occurred:
java.lang.RuntimeException: SimTK Exception thrown at State.cpp:974:
  Error detected by Simbody method getCacheEntry: State Cache entry was out of date at Stage Position. This entry depends on version 7 of
  Stage Position but was last updated at version 0.
  (Required condition 'version == m_dependsOnVersionWhenLastComputed' was not met.)


	at org.opensim.modeling.opensimSimulationJNI.Smith2018ArticularContactForce_computePotentialEnergy(Native Method)

	at org.opensim.modeling.Smith2018ArticularContactForce.computePotentialEnergy(Smith2018ArticularContactForce.java:1030)
```
Do you know if there is a workaround in MATLAB or this needs to be fixed in the C++ code?
Thank you,
Luca

**Comment by modenaxe** [comment]
I also attach a small example to replicate the issue (
[JAM issue.zip](https://github.com/opensim-jam-org/opensim-core/files/12308206/JAM.issue.zip)), hopefully it will help.
Cheers,
Luca
